-- +goose Up
-- All primary and foreign keys are UUID (docs/architecture/08-uuid-primary-keys.md):
-- values are generated by the service layer (UUIDv7) before INSERT, so the
-- columns carry no defaults and no sequences exist.

CREATE TABLE roles (
    id     UUID PRIMARY KEY,
    name   VARCHAR(32) NOT NULL UNIQUE,
    remark VARCHAR(128) NOT NULL DEFAULT ''
);

CREATE TABLE permissions (
    id   UUID PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(64) NOT NULL
);

CREATE TABLE admin_users (
    id             UUID PRIMARY KEY,
    username       VARCHAR(32) NOT NULL UNIQUE,
    password_hash  VARCHAR(255) NOT NULL,
    token_version  BIGINT NOT NULL DEFAULT 1
        CONSTRAINT admin_users_token_version_positive CHECK (token_version > 0),
    role_id        UUID NOT NULL CONSTRAINT admin_users_role_id_fk REFERENCES roles(id),
    enabled        BOOLEAN NOT NULL DEFAULT true,
    last_login_at  TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE role_permissions (
    role_id       UUID NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id UUID NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE users (
    id             UUID PRIMARY KEY,
    openid         VARCHAR(64) NOT NULL UNIQUE,
    nickname       VARCHAR(64) NOT NULL DEFAULT '',
    avatar_url     TEXT NOT NULL DEFAULT '',
    points_balance BIGINT NOT NULL DEFAULT 0
        CONSTRAINT users_points_balance_nonnegative CHECK (points_balance >= 0),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE products (
    id           UUID PRIMARY KEY,
    name         VARCHAR(128) NOT NULL,
    description  TEXT NOT NULL DEFAULT '',
    main_image   TEXT NOT NULL DEFAULT '',
    price_points BIGINT NOT NULL
        CONSTRAINT products_price_points_positive CHECK (price_points > 0),
    stock        INT NOT NULL DEFAULT 0
        CONSTRAINT products_stock_nonnegative CHECK (stock >= 0),
    status       VARCHAR(16) NOT NULL DEFAULT 'on_sale'
        CONSTRAINT products_status_valid CHECK (status IN ('on_sale', 'off_sale')),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_products_status_id
    ON products (status, id DESC);

CREATE TABLE user_addresses (
    id         UUID PRIMARY KEY,
    user_id    UUID NOT NULL CONSTRAINT user_addresses_user_id_fk REFERENCES users(id) ON DELETE CASCADE,
    receiver   VARCHAR(32) NOT NULL,
    phone      VARCHAR(20) NOT NULL,
    region     VARCHAR(64) NOT NULL,
    detail     VARCHAR(255) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT false,
    version    BIGINT NOT NULL DEFAULT 1
        CONSTRAINT user_addresses_version_positive CHECK (version > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_addresses_user
    ON user_addresses (user_id, id);

CREATE UNIQUE INDEX uq_default_address
    ON user_addresses (user_id)
    WHERE is_default = true;

CREATE TABLE cart_items (
    id         UUID PRIMARY KEY,
    user_id    UUID NOT NULL CONSTRAINT cart_items_user_id_fk REFERENCES users(id) ON DELETE CASCADE,
    product_id UUID NOT NULL CONSTRAINT cart_items_product_id_fk REFERENCES products(id),
    quantity   INT NOT NULL
        CONSTRAINT cart_items_quantity_positive CHECK (quantity > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT cart_items_user_id_product_id_key UNIQUE (user_id, product_id)
);

CREATE TABLE orders (
    id                   UUID PRIMARY KEY,
    order_no             VARCHAR(32) NOT NULL UNIQUE,
    user_id              UUID NOT NULL CONSTRAINT orders_user_id_fk REFERENCES users(id),
    client_token         VARCHAR(64) NOT NULL,
    request_hash         CHAR(64) NOT NULL,
    status               VARCHAR(20) NOT NULL
        CONSTRAINT orders_status_valid CHECK (status IN ('paid', 'shipped', 'completed', 'refund_requested', 'refunded')),
    total_points         BIGINT NOT NULL
        CONSTRAINT orders_total_points_positive CHECK (total_points > 0),
    receiver             VARCHAR(32) NOT NULL,
    phone                VARCHAR(20) NOT NULL,
    address              VARCHAR(512) NOT NULL,
    refund_reason        VARCHAR(255) NOT NULL DEFAULT '',
    refund_reject_reason VARCHAR(255) NOT NULL DEFAULT '',
    refund_reviewed_by   UUID CONSTRAINT orders_refund_reviewed_by_fk REFERENCES admin_users(id) ON DELETE RESTRICT,
    refund_reviewed_at   TIMESTAMPTZ,
    paid_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    shipped_by           UUID CONSTRAINT orders_shipped_by_fk REFERENCES admin_users(id) ON DELETE RESTRICT,
    shipped_at           TIMESTAMPTZ,
    completed_at         TIMESTAMPTZ,
    refunded_at          TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT orders_user_id_client_token_key UNIQUE (user_id, client_token),
    CONSTRAINT orders_client_token_not_blank CHECK (btrim(client_token) <> ''),
    CONSTRAINT orders_shipped_fields_consistent CHECK (
        status NOT IN ('paid', 'shipped', 'completed', 'refund_requested', 'refunded')
        OR
        (status IN ('shipped', 'completed') AND shipped_by IS NOT NULL AND shipped_at IS NOT NULL)
        OR
        (status = 'paid' AND shipped_by IS NULL AND shipped_at IS NULL)
        OR
        (status IN ('refund_requested', 'refunded') AND (shipped_by IS NULL) = (shipped_at IS NULL))
    ),
    CONSTRAINT orders_completed_at_consistent CHECK (
        status NOT IN ('paid', 'shipped', 'completed', 'refund_requested', 'refunded')
        OR
        (status IN ('paid', 'shipped') AND completed_at IS NULL)
        OR
        (status = 'completed' AND completed_at IS NOT NULL)
        OR
        (status IN ('refund_requested', 'refunded'))
    ),
    CONSTRAINT orders_refunded_at_consistent CHECK (
        status NOT IN ('paid', 'shipped', 'completed', 'refund_requested', 'refunded')
        OR
        ((status = 'refunded') = (refunded_at IS NOT NULL))
    )
);

CREATE INDEX idx_orders_user_status
    ON orders (user_id, status, created_at DESC, id DESC);

CREATE INDEX idx_orders_status_created
    ON orders (status, created_at DESC, id DESC);

CREATE TABLE order_items (
    id             UUID PRIMARY KEY,
    order_id       UUID NOT NULL CONSTRAINT order_items_order_id_fk REFERENCES orders(id) ON DELETE CASCADE,
    product_id     UUID NOT NULL CONSTRAINT order_items_product_id_fk REFERENCES products(id),
    product_name   VARCHAR(128) NOT NULL,
    product_image  TEXT NOT NULL DEFAULT '',
    price_snapshot BIGINT NOT NULL
        CONSTRAINT order_items_price_snapshot_positive CHECK (price_snapshot > 0),
    quantity       INT NOT NULL
        CONSTRAINT order_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT order_items_order_id_product_id_key UNIQUE (order_id, product_id)
);

CREATE INDEX idx_order_items_order
    ON order_items (order_id);

CREATE TABLE points_ledger (
    id                  UUID PRIMARY KEY,
    user_id             UUID NOT NULL CONSTRAINT points_ledger_user_id_fk REFERENCES users(id),
    order_id            UUID CONSTRAINT points_ledger_order_id_fk REFERENCES orders(id),
    event_key           VARCHAR(96) NOT NULL UNIQUE,
    request_hash        CHAR(64),
    type                VARCHAR(20) NOT NULL
        CONSTRAINT points_ledger_type_valid CHECK (type IN ('order_pay', 'order_refund', 'signup_bonus', 'admin_adjust')),
    delta               BIGINT NOT NULL
        CONSTRAINT points_ledger_delta_nonzero CHECK (delta <> 0),
    balance_after       BIGINT NOT NULL
        CONSTRAINT points_ledger_balance_after_nonnegative CHECK (balance_after >= 0),
    created_by_admin_id UUID CONSTRAINT points_ledger_created_by_admin_id_fk REFERENCES admin_users(id) ON DELETE RESTRICT,
    remark              VARCHAR(255) NOT NULL DEFAULT '',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT points_ledger_direction_valid CHECK (
        (type = 'order_pay' AND order_id IS NOT NULL AND delta < 0 AND created_by_admin_id IS NULL)
        OR
        (type = 'order_refund' AND order_id IS NOT NULL AND delta > 0 AND created_by_admin_id IS NOT NULL)
        OR
        (type = 'signup_bonus' AND order_id IS NULL AND delta > 0 AND created_by_admin_id IS NULL)
        OR
        (type = 'admin_adjust' AND order_id IS NULL AND created_by_admin_id IS NOT NULL)
    ),
    CONSTRAINT points_ledger_admin_remark_not_blank CHECK (type <> 'admin_adjust' OR btrim(remark) <> ''),
    CONSTRAINT points_ledger_admin_request_hash_required CHECK (
        (type = 'admin_adjust' AND request_hash IS NOT NULL)
        OR
        (type <> 'admin_adjust' AND request_hash IS NULL)
    )
);

CREATE INDEX idx_ledger_user_id
    ON points_ledger (user_id, id DESC);

CREATE INDEX idx_ledger_order
    ON points_ledger (order_id);

CREATE UNIQUE INDEX uq_signup_bonus_user
    ON points_ledger (user_id)
    WHERE type = 'signup_bonus';

CREATE UNIQUE INDEX uq_order_pay
    ON points_ledger (order_id)
    WHERE type = 'order_pay';

CREATE UNIQUE INDEX uq_order_refund
    ON points_ledger (order_id)
    WHERE type = 'order_refund';

CREATE TABLE audit_logs (
    id             UUID PRIMARY KEY,
    actor_admin_id UUID CONSTRAINT audit_logs_actor_admin_id_fk REFERENCES admin_users(id) ON DELETE RESTRICT,
    actor_role     VARCHAR(32) NOT NULL,
    action         VARCHAR(64) NOT NULL,
    target_type    VARCHAR(64) NOT NULL,
    target_id      UUID,
    result         VARCHAR(16) NOT NULL
        CONSTRAINT audit_logs_result_valid CHECK (result IN ('success', 'failure')),
    before_data    JSONB,
    after_data     JSONB,
    trace_id       VARCHAR(128) NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_actor_time
    ON audit_logs (actor_admin_id, created_at DESC);

CREATE INDEX idx_audit_target_time
    ON audit_logs (target_type, target_id, created_at DESC);

CREATE FUNCTION reject_audit_log_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'audit_logs is append-only';
END;
$$;

CREATE TRIGGER audit_logs_append_only
BEFORE UPDATE OR DELETE ON audit_logs
FOR EACH ROW EXECUTE FUNCTION reject_audit_log_mutation();

CREATE TRIGGER audit_logs_append_only_truncate
BEFORE TRUNCATE ON audit_logs
FOR EACH STATEMENT EXECUTE FUNCTION reject_audit_log_mutation();
