-- +goose Up
-- Marketing domain: coupon templates and the coupons buyers hold
-- (docs/architecture/07-coupon-pay-lifecycle.md §3). Primary and foreign keys
-- follow docs/architecture/08-uuid-primary-keys.md: values are generated by
-- the service layer (UUIDv7) before INSERT, so the columns carry no defaults
-- and no sequences exist. (Repo convention: forward migrations only, no down
-- sections.)

CREATE TABLE coupon_templates (
    id               UUID PRIMARY KEY,
    name             VARCHAR(64) NOT NULL,
    threshold_points BIGINT NOT NULL
        CONSTRAINT coupon_templates_threshold_points_positive CHECK (threshold_points > 0),
    discount_points  BIGINT NOT NULL
        CONSTRAINT coupon_templates_discount_points_positive CHECK (discount_points > 0),
    total_count      INT NOT NULL
        CONSTRAINT coupon_templates_total_count_positive CHECK (total_count > 0),
    per_user_limit   INT NOT NULL
        CONSTRAINT coupon_templates_per_user_limit_positive CHECK (per_user_limit > 0),
    -- Service-maintained issue counter; the conditional UPDATE ... WHERE
    -- received_count < total_count is the oversell backstop, this CHECK is the
    -- last line of defence.
    received_count   INT NOT NULL DEFAULT 0,
    valid_from       TIMESTAMPTZ NOT NULL,
    valid_until      TIMESTAMPTZ NOT NULL,
    status           VARCHAR(16) NOT NULL DEFAULT 'active',
    -- discount < threshold keeps pay_points = total_points - discount_points
    -- strictly positive for every order that actually redeems a coupon
    -- (original price >= threshold > discount).
    CONSTRAINT coupon_templates_discount_below_threshold CHECK (discount_points < threshold_points),
    CONSTRAINT coupon_templates_received_count_within_total CHECK (
        received_count >= 0 AND received_count <= total_count
    ),
    CONSTRAINT coupon_templates_validity_window CHECK (valid_until > valid_from),
    CONSTRAINT coupon_templates_status_valid CHECK (status IN ('active', 'halted'))
);

CREATE TABLE user_coupons (
    id          UUID PRIMARY KEY,
    user_id     UUID NOT NULL
        CONSTRAINT user_coupons_user_id_fk REFERENCES users(id) ON DELETE CASCADE,
    template_id UUID NOT NULL
        CONSTRAINT user_coupons_template_id_fk REFERENCES coupon_templates(id),
    status      VARCHAR(16) NOT NULL DEFAULT 'available',
    -- Nullable: records the most recent order that held or redeemed this
    -- coupon. Cancellation releases the coupon but keeps the value as history.
    order_id    UUID
        CONSTRAINT user_coupons_order_id_fk REFERENCES orders(id),
    -- Idempotency-Key of the receive request; NULL on every non-receive path.
    request_id  VARCHAR(64),
    CONSTRAINT user_coupons_status_valid CHECK (status IN ('available', 'held', 'used', 'expired'))
);

-- A coupon is occupied by at most one in-flight or settled order at a time;
-- once released, the same coupon can be held again by a new order.
CREATE UNIQUE INDEX uq_user_coupons_order
    ON user_coupons (order_id)
    WHERE status IN ('held', 'used');

-- Receive idempotency, scoped per buyer: replaying the same request_id returns
-- the original coupon, a different template under the same key is a conflict.
CREATE UNIQUE INDEX uq_user_coupons_request
    ON user_coupons (user_id, request_id)
    WHERE request_id IS NOT NULL;

-- "My coupons" and the checkout coupon picker list newest first; UUIDv7 keeps
-- the id DESC tiebreak time-ordered (08-uuid-primary-keys.md §3).
CREATE INDEX idx_user_coupons_user_status
    ON user_coupons (user_id, status, id DESC);

-- Permission seeds bypass the service-layer generator: primary keys are fixed
-- UUID literals frozen with this migration, continuing the 0002/0003 series.
INSERT INTO permissions (id, code, name)
VALUES
    ('00000000-0000-7000-8000-70000000000d', 'coupon:read', 'Read coupon templates'),
    ('00000000-0000-7000-8000-70000000000e', 'coupon:write', 'Write coupon templates')
ON CONFLICT (code) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN ('coupon:read', 'coupon:write')
WHERE r.name IN ('super_admin', 'operator')
ON CONFLICT DO NOTHING;