package storage

import (
	"bytes"
	"encoding/base64"
	"errors"
	"hash/crc32"
	"image"
	"image/jpeg"
	"image/png"
	"testing"
)

// testWebP is a valid 2x2 WebP generated by Pillow 12.2.0. It is embedded so
// tests do not depend on an encoder (golang.org/x/image/webp is decode-only).
const testWebP = "UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoCAAIAAUAmJaACdLoAArrbQIAA/vbhrfWUkkkp2R28OWPYqv/UGf+Wh/6tD9bgAAA="

func generateJPEG(t *testing.T, width, height int) []byte {
	t.Helper()
	img := image.NewRGBA(image.Rect(0, 0, width, height))
	var buf bytes.Buffer
	if err := jpeg.Encode(&buf, img, nil); err != nil {
		t.Fatalf("encode test JPEG: %v", err)
	}
	return buf.Bytes()
}

func generatePNG(t *testing.T, width, height int) []byte {
	t.Helper()
	img := image.NewRGBA(image.Rect(0, 0, width, height))
	var buf bytes.Buffer
	if err := png.Encode(&buf, img); err != nil {
		t.Fatalf("encode test PNG: %v", err)
	}
	return buf.Bytes()
}

func decodeTestWebP(t *testing.T) []byte {
	t.Helper()
	data, err := base64.StdEncoding.DecodeString(testWebP)
	if err != nil {
		t.Fatalf("decode test WebP: %v", err)
	}
	return data
}

func TestValidObjectKeyRejectsUntrustedInput(t *testing.T) {
	valid := []string{
		"01234567-89ab-cdef-0123-456789abcdef.jpg",
		"01234567-89ab-cdef-0123-456789abcdef.png",
		"01234567-89ab-cdef-0123-456789abcdef.webp",
	}
	for _, key := range valid {
		if !ValidObjectKey(key) {
			t.Fatalf("expected %q to be a valid object key", key)
		}
	}
	invalid := []string{
		"",
		"../etc/passwd",
		"../../tmp/evil.jpg",
		"evil.png",
		"/absolute/path.jpg",
		"01234567-89ab-cdef-0123-456789abcdef.exe",
		"01234567-89ab-cdef-0123-456789abcdef.JPG",
		"01234567-89ab-cdef-0123-456789abcdef",
		"01234567-89ab-cdef-0123-456789abcdef.jpg/extra",
		"a/b/01234567-89ab-cdef-0123-456789abcdef.jpg",
	}
	for _, key := range invalid {
		if ValidObjectKey(key) {
			t.Fatalf("expected %q to be rejected as an object key", key)
		}
	}
}

func TestValidateImageAcceptsJPEGPNGAndWebP(t *testing.T) {
	cases := []struct {
		name    string
		content []byte
		want    ImageFormat
	}{
		{"jpeg", generateJPEG(t, 8, 6), FormatJPEG},
		{"png", generatePNG(t, 8, 6), FormatPNG},
		{"webp", decodeTestWebP(t), FormatWebP},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			info, err := ValidateImage(tc.content, 1<<20, 25_000_000)
			if err != nil {
				t.Fatalf("ValidateImage: %v", err)
			}
			if info.Format != tc.want {
				t.Fatalf("format = %s, want %s", info.Format, tc.want)
			}
			if info.Width <= 0 || info.Height <= 0 {
				t.Fatalf("invalid dimensions %dx%d", info.Width, info.Height)
			}
			if info.Size != int64(len(tc.content)) {
				t.Fatalf("size = %d, want %d", info.Size, len(tc.content))
			}
		})
	}
}

func TestValidateImageRejectsMIMESpoofing(t *testing.T) {
	// A JPEG payload carrying the PNG magic bytes: the signature decoder must
	// reject it even though the trailing bytes are a valid JPEG stream.
	spoofed := append([]byte{0x89, 'P', 'N', 'G', 0x0D, 0x0A, 0x1A, 0x0A}, generateJPEG(t, 4, 4)...)
	if _, err := ValidateImage(spoofed, 1<<20, 25_000_000); !errors.Is(err, ErrInvalidImage) {
		t.Fatalf("spoofed PNG-in-JPEG error = %v, want ErrInvalidImage", err)
	}
	// A plain text file claiming to be an image has no magic number at all.
	text := []byte("this is not an image at all")
	if _, err := ValidateImage(text, 1<<20, 25_000_000); !errors.Is(err, ErrUnsupportedFormat) {
		t.Fatalf("text payload error = %v, want ErrUnsupportedFormat", err)
	}
}

func TestValidateImageRejectsInvalidImageBytes(t *testing.T) {
	// Truncated PNG: the magic is right but the payload is incomplete.
	truncated := generatePNG(t, 4, 4)[:12]
	if _, err := ValidateImage(truncated, 1<<20, 25_000_000); !errors.Is(err, ErrInvalidImage) {
		t.Fatalf("truncated PNG error = %v, want ErrInvalidImage", err)
	}
	// Empty payload.
	if _, err := ValidateImage(nil, 1<<20, 25_000_000); !errors.Is(err, ErrInvalidImage) {
		t.Fatalf("empty payload error = %v, want ErrInvalidImage", err)
	}
}

func TestValidateImageRejectsOversizedFile(t *testing.T) {
	content := generatePNG(t, 4, 4)
	if _, err := ValidateImage(content, int64(len(content)-1), 25_000_000); !errors.Is(err, ErrImageTooLarge) {
		t.Fatalf("oversized error = %v, want ErrImageTooLarge", err)
	}
}

func TestValidateImageRejectsPixelLimit(t *testing.T) {
	// A plain 100x100 PNG passes when the limit is generous.
	content := generatePNG(t, 100, 100)
	if _, err := ValidateImage(content, 1<<20, 25_000_000); err != nil {
		t.Fatalf("baseline image rejected: %v", err)
	}
	// The same image fails when the limit is below 100*100.
	if _, err := ValidateImage(content, 1<<20, 9999); !errors.Is(err, ErrTooManyPixels) {
		t.Fatalf("pixel-limited error = %v, want ErrTooManyPixels", err)
	}
}

func TestValidateImageRejectsDecoderBombBeforeAllocation(t *testing.T) {
	// A JPEG whose header advertises 100000x100000 dimensions but whose
	// payload is small must be rejected by the pixel limit before a full
	// decode attempts to allocate the bitmap. The baseline limit is 1M px.
	content := buildHugeDimensionPNGHeader(t)
	if _, err := ValidateImage(content, 1<<20, 25_000_000); !errors.Is(err, ErrTooManyPixels) {
		t.Fatalf("bomb error = %v, want ErrTooManyPixels", err)
	}
}

// buildHugeDimensionPNGHeader manufactures a PNG whose IHDR advertises huge
// dimensions and whose remaining payload is a valid small PNG stream. The
// IHDR CRC is recomputed so the decoder trusts the header and surfaces the
// dimensions before the pixel limit rejects the image without allocating the
// full bitmap.
func buildHugeDimensionPNGHeader(t *testing.T) []byte {
	t.Helper()
	small := generatePNG(t, 4, 4)
	// The PNG signature plus the full IHDR chunk is 33 bytes. Advertise
	// 100000x100000 dimensions (0x000186A0) so the pixel limit is hit before
	// the full decode.
	header := append([]byte(nil), small[:33]...)
	header[16] = 0x00
	header[17] = 0x01
	header[18] = 0x86
	header[19] = 0xA0
	header[20] = 0x00
	header[21] = 0x01
	header[22] = 0x86
	header[23] = 0xA0
	// PNG chunk layout: len(4) type(4) data(13) crc(4). The CRC covers the
	// type and data bytes (offsets 12..28).
	crc := crc32.ChecksumIEEE(header[12:29])
	header[29] = byte(crc >> 24)
	header[30] = byte(crc >> 16)
	header[31] = byte(crc >> 8)
	header[32] = byte(crc)
	return header
}
