import { execFileSync } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile, mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";
import { parse } from "yaml";

const root = resolve(import.meta.dirname, "../..");
const contract = resolve(root, "docs/api/openapi.yaml");
const redocly = resolve(root, "tools/openapi/redocly.yaml");
const outputs = [
  resolve(root, "miniapp/src/services/generated/api.d.ts"),
  resolve(root, "admin/src/services/generated/api.d.ts"),
];

const publicInt64Pointers = [
  "#/components/parameters/ProductId/schema",
  "#/components/parameters/CartItemId/schema",
  "#/components/parameters/AddressId/schema",
  "#/components/parameters/OrderId/schema",
  "#/components/parameters/RoleId/schema",
  "#/components/parameters/AdminUserId/schema",
  "#/components/schemas/User/properties/id",
  "#/components/schemas/User/properties/points_balance",
  "#/components/schemas/Product/properties/id",
  "#/components/schemas/Product/properties/price_points",
  "#/components/schemas/ProductWriteRequest/properties/price_points",
  "#/components/schemas/CartItem/properties/id",
  "#/components/schemas/CartItem/properties/product_id",
  "#/components/schemas/Address/properties/id",
  "#/components/schemas/Address/properties/version",
  "#/components/schemas/OrderItem/properties/product_id",
  "#/components/schemas/OrderItem/properties/price_snapshot",
  "#/components/schemas/Order/properties/id",
  "#/components/schemas/Order/properties/total_points",
  "#/components/schemas/LedgerEntry/properties/id",
  "#/components/schemas/LedgerEntry/properties/order_id",
  "#/components/schemas/LedgerEntry/properties/delta",
  "#/components/schemas/LedgerEntry/properties/balance_after",
  "#/components/schemas/Role/properties/id",
  "#/components/schemas/AdminUser/properties/id",
  "#/components/schemas/AdminUserUpdateRequest/properties/role_id",
  "#/components/schemas/AdminLoginResponse/properties/data/properties/admin_id",
  "#/components/schemas/CartItemCreateRequest/properties/product_id",
  "#/components/schemas/OrderCreateRequest/properties/cart_item_ids/items",
  "#/components/schemas/OrderCreateRequest/properties/address_id",
  "#/components/schemas/PointsAdjustRequest/properties/user_id",
  "#/components/schemas/PointsAdjustRequest/properties/delta",
];

const unsignedInt64Patterns = new Set(["^[0-9]+$", "^[1-9][0-9]*$"]);
const signedInt64Patterns = new Set(["^-?[0-9]+$", "^-?[1-9][0-9]*$"]);

const generatedHeader = `/**
 * Generated from docs/api/openapi.yaml. Do not edit this file by hand.
 * Runtime requests must cross the app-specific transport adapter boundary.
 */
export interface ApiRequest {
  method: string;
  path: string;
  headers?: Record<string, string>;
  query?: Record<string, string | number | boolean | undefined>;
  body?: unknown;
}

export interface ApiResponse<T = unknown> {
  data: T;
  statusCode: number;
  headers: Record<string, string>;
  trace_id?: string;
}

export type ApiTransport = (request: ApiRequest) => Promise<ApiResponse>;

`;

function generateTo(output: string): void {
  execFileSync(
    "openapi-typescript",
    [
      contract,
      "--redocly",
      redocly,
      "--output",
      output,
      // openapi-typescript v7 turns every property carrying a `default` into a
      // required one (openapi-ts/openapi-typescript#2012). The contract is the
      // authority: AddressCreateRequest.is_default is optional, so the buyer
      // page can omit the key when the default switch is unchecked.
      "--default-non-nullable",
      "false",
    ],
    // Windows: local bin shims are .cmd files that spawnSync only resolves
    // through a shell; the args here are repo-relative constants.
    { cwd: root, stdio: "inherit", ...(process.platform === "win32" ? { shell: true } : {}) },
  );
}

function resolvePointer(document: unknown, pointer: string): Record<string, unknown> | undefined {
  return pointer
    .slice(2)
    .split("/")
    .map((part) => part.replaceAll("~1", "/").replaceAll("~0", "~"))
    .reduce<unknown>((current, part) => {
      if (current === null || typeof current !== "object") return undefined;
      return (current as Record<string, unknown>)[part];
    }, document) as Record<string, unknown> | undefined;
}

function collectPublicInt64Pointers(value: unknown, pointer = "#", result: string[] = []): string[] {
  if (value === null || typeof value !== "object") return result;
  if ((value as Record<string, unknown>)["x-public-int64"] === true) result.push(pointer);
  for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
    const escapedKey = key.replaceAll("~", "~0").replaceAll("/", "~1");
    collectPublicInt64Pointers(child, `${pointer}/${escapedKey}`, result);
  }
  return result;
}

function assertNoInt64Format(value: unknown, pointer = "#"): void {
  if (value === null || typeof value !== "object") return;
  const record = value as Record<string, unknown>;
  if (record.format === "int64") {
    throw new Error(`${pointer} must not use OpenAPI format int64; mark it as a string public int64 schema`);
  }
  for (const [key, child] of Object.entries(record)) {
    const escapedKey = key.replaceAll("~", "~0").replaceAll("/", "~1");
    assertNoInt64Format(child, `${pointer}/${escapedKey}`);
  }
}

function validatePublicInt64(document: unknown): void {
  assertNoInt64Format(document);
  const actualPointers = collectPublicInt64Pointers(document).sort();
  const expectedPointers = [...publicInt64Pointers].sort();
  if (JSON.stringify(actualPointers) !== JSON.stringify(expectedPointers)) {
    throw new Error(
      `public int64 marker set changed; expected ${expectedPointers.length} fields, found ${actualPointers.length}`,
    );
  }

  for (const pointer of publicInt64Pointers) {
    const schema = resolvePointer(document, pointer);
    if (!schema || schema["x-public-int64"] !== true) {
      throw new Error(`${pointer} must be marked with x-public-int64: true`);
    }
    const types = Array.isArray(schema.type) ? schema.type : [schema.type];
    const nonNullTypes = types.filter((type) => type !== "null");
    if (nonNullTypes.length !== 1 || nonNullTypes[0] !== "string") {
      throw new Error(`${pointer} must use string only, with optional null; number/integer is forbidden`);
    }
    if (schema.format !== undefined) throw new Error(`${pointer} must not define format`);
    const signed = schema["x-public-int64-signed"] === true;
    const patterns = signed ? signedInt64Patterns : unsignedInt64Patterns;
    if (typeof schema.pattern !== "string" || !patterns.has(schema.pattern)) {
      throw new Error(`${pointer} must use a decimal ${signed ? "signed" : "non-negative"} pattern`);
    }
    if (typeof schema.example !== "string") throw new Error(`${pointer} must provide a string example`);
  }
}

async function withGeneratedFile(output: string, action: (tempOutput: string) => Promise<void>): Promise<void> {
  const temporaryDirectory = await mkdtemp(resolve(tmpdir(), "shop-mall-openapi-"));
  const temporaryOutput = resolve(temporaryDirectory, "api.d.ts");
  try {
    generateTo(temporaryOutput);
    const generated = await readFile(temporaryOutput, "utf8");
    await writeFile(temporaryOutput, generatedHeader + generated);
    await action(temporaryOutput);
  } finally {
    await rm(temporaryDirectory, { recursive: true, force: true });
  }
}

async function generate(): Promise<void> {
  const checkOnly = process.argv.includes("--check");
  const contractSource = await readFile(contract, "utf8");
  validatePublicInt64(parse(contractSource));

  for (const output of outputs) {
    await withGeneratedFile(output, async (temporaryOutput) => {
      const generated = await readFile(temporaryOutput, "utf8");
      if (checkOnly) {
        let existing: string;
        try {
          existing = await readFile(output, "utf8");
        } catch {
          throw new Error(`missing generated output: ${output}`);
        }
        if (existing !== generated) {
          throw new Error(`generated output is stale: ${output}; run pnpm --filter @shop-mall/openapi generate`);
        }
        return;
      }

      await mkdir(dirname(output), { recursive: true });
      await writeFile(output, generated);
    });
  }
}

await generate();
