// Package uid defines the resource identifier type shared by all domains.
// IDs are UUIDv7 values generated by the service layer before INSERT, as
// specified in docs/architecture/08-uuid-primary-keys.md. The alias to
// uuid.UUID keeps String, Compare and JSON marshaling available at every
// call site.
package uid

import (
	"errors"

	"github.com/google/uuid"
)

// ID is a resource primary key or reference to one.
type ID = uuid.UUID

// New returns a fresh time-ordered UUIDv7 so "ORDER BY id DESC" keeps the
// newest-first semantics the legacy BIGSERIAL indexes relied on.
func New() ID {
	return uuid.Must(uuid.NewV7())
}

// IsZero reports whether id is the zero UUID (the "unset" sentinel the
// numeric era expressed as uid.IsZero(id)).
func IsZero(id ID) bool {
	return id == uuid.Nil
}

// ErrInvalidID reports input that is not a canonical UUID string.
var ErrInvalidID = errors.New("invalid uuid")

// ParseCanonical accepts exactly the canonical lowercase hyphenated form
// (the encoding frozen for event_key and JWT subjects). lenient forms such
// as braces, URN prefixes or uppercase hex are rejected.
func ParseCanonical(text string) (ID, error) {
	id, err := uuid.Parse(text)
	if err != nil || id.String() != text {
		return ID{}, ErrInvalidID
	}
	return id, nil
}
